### ISSUE TITLE
does design-system recommended to customise and use it in production?

### ISSUE THREAD

**Issue by drrcodebase** [UKHomeOffice/design-system#315]
Hi @daniel-ac-martin ,

I have taken the design-system code and  customised (added custom pages  and removed existing pages ).  it's perfectly suites for my requirements. working for one of the homeoffice internal sites . is this design framework recommended to use it  in production.

Thanks in advance

**Comment by daniel-ac-martin** [comment]
Hi @drrcodebase.

> is this design framework recommended to use it in production.

Not yet. Although, that is our longer term aspiration. We'd like to bridge the gap between design and implementation. So our components are generally intended to be used in production as well as in prototypes. We also have a 'project' generator in addition to the prototype generator. We've yet to document this on the design system website but there is some [light-touch documentation available on the parent project](https://not-gov.uk/get-started). (If you replace `@not-govuk` with `@hods` you should get a version that builds on this design system.)

> I have taken the design-system code and customised (added custom pages and removed existing pages ).

If you've literally copied this code repo, that's probably not ideal. Following the documentation I've listed above and running `npm init @hods project` is probably what you want.

> it's perfectly suites for my requirements

I'd be happy to talk through you requirements on Slack if you like?

In terms of what is missing for production, I'd say there's the following:
- We need more documentation as many important features are hard to discover
- We need to improve our handling of sessions, especially when it comes to OpenID Connect.
- We probably need a concept of 'models' along with a generator for them, so that people can easily set up a flow of data from their database into their components. (Along with applying RBAC for security.)
- [The forms framework](https://not-gov.uk/components?name=Form) is only a POC and needs an overhaul before it can be used in non-trivial situations.

Overall, I'd say it's at a level where a team could start to use it in production, but they would probably need to be willing to work with me when they run into problems.

**Comment by drrcodebase** [comment]
Thanks a lot @daniel-ac-martin  for your valuable replay.  I am happy to show my project and discuss further . could you please add me to the  slack channel , as I am not able to join.

**Comment by daniel-ac-martin** [comment]
@drrcodebase: I'm not sure what your username would be. (And you don't have your name on your GitHub profile.) I'm `@daniel` if you want to message me. Otherwise, you could probably work out my 'digital' e-mail and contact me there.
