### ISSUE TITLE
Alert component inaccessibility

### ISSUE THREAD

**Issue by benjest85** [UKHomeOffice/design-system#578]
I'm working on updates for the alert component, primarily due to the colour contrast when links are used as per attached screenshot (left hand example). 

I've used the existing design work from the Figma file to create new alert components (shown right hand side) that include information (blue), success (green) and error (red). This component needs to be suitable for both white and grey backgrounds.

I'll be looking to test these components as part of ongoing UR, preferably in journeys that naturally include alerts.

<img width="1195" alt="image" src="https://github.com/UKHomeOffice/design-system/assets/74179403/a21a7ebc-bb90-4534-89d4-5a132a9fb55d">

**Comment by benjest85** [comment]
During the DSWG meeting on 6th June we agreed that the most simple solution would be to add guidance to the [design system page ](https://design.homeoffice.gov.uk/components?name=Alert)

The most suitable place might be under the accessibility heading and explain to designers that they should remember to make any links **bold** when used in this component. Sarah will kindly look at wording which can be added to this section.

**Comment by Sarah-Lombardi** [comment]
This is how I'd incorporate it into the existing content (italics only used here for emphasis and should not appear online):

### Writing for this component
Try to keep alerts to one or two lines of text and not necessarily in full sentences, given the lack of space. If the text does not end in a link and is a full sentence, include a full stop.

Tell users what to do next. If you can, give them a link that will take them directly to further support or the next action.

Only use bold for headings _and links._

If the alert is about people, make sure your content is dynamic and personalised. Use ‘person’ when it’s about one person and ‘people’ for more than one and include names if you can.

### Accessibility
All users benefit from clear, visible notification messages which are presented in a consistent, predictable way. See the [notifications guidance](https://design.homeoffice.gov.uk/accessibility/notifications) for more information.

_Make the link text bold so that it contrasts enough with the background colours._

In the Atlas caseworking system, it was found this alert should sit under the H1 heading level.

**Comment by Sarah-Lombardi** [comment]
And then we just have to update all the examples to show bold text.

**Comment by benjest85** [comment]
Pages updated and submitted for PR
